### PR TITLE
Feature/sr

### PR DESCRIPTION
**Pull request by tznind**
## Proposed Changes

Adds SR modality template

## Types of changes

What types of changes does your code introduce? Tick all that apply.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation-Only Update (if none of the other choices apply)
  - In this case, ensure that the message of the head commit from the source branch is prefixed with `[skip ci]`

## Checklist

By opening this PR, I confirm that I have:

- [x] Reviewed the [contributing](https://github.com/HicServices/DicomTypeTranslation/blob/master/CONTRIBUTING.md) guidelines for this repository
- [x] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
- [x] Updated any relevant API documentation
- [x] Created or updated any tests if relevant
- [x] Accurately updated the [CHANGELOG](https://github.com/HicServices/DicomTypeTranslation/blob/master/CHANGELOG.md)
- [x] Listed myself in the [CONTRIBUTORS](https://github.com/HicServices/DicomTypeTranslation/blob/master/CONTRIBUTORS.md) file 🚀
- [x] Requested a review by one of the repository maintainers

### CODE REVIEW

**Review by rkm — APPROVED** [review]
Looks good, but I'll repeat the question I asked in Mattermost here -- are there any SR-specific tags that we're aware of which would be useful to cohort building? I'm thinking tags that point to other referenced DICOM objects e.g. https://dicom.innolitics.com/ciods/basic-text-sr/sr-document-general/0008114a/00081155

**Review by howff — COMMENTED** [review]
I wonder if it's worth including SOPClassUID in the template because that's what defines the SR type (eg. Comprehensive vs Dose Report).

I'm having a think about whether simple references can be included too.

**Comment by howff** [comment]
Typical references I've seen are a BulkDataURI tag with content like "file://beegfs..blah../X.1.2.3"
but those tags can be inside many others, for example
0042,0011 "EncapsulatedDocument" has a BulkDataURI child
7FE0,0010 "PixelData"
etc
The VR (type) can be OB,OW (byte,word) or UR (URL)

**Comment by tznind** [comment]
If there are reliable specific pathways to tags I can handle them e.g.  ProcedureCodeSequence->CodeValue.  The setting currently only supports navigating from the root.

@rkm sounds like you want

- Referenced Instance Sequence=>Referenced SOP Class UID
- Referenced Instance Sequence=>Referenced SOP Instance UID 
- Referenced Instance Sequence=>Purpose of Reference Code Sequence

Is `Referenced Instance Sequence` a root tag or does it appear only in arbitrary subsequences?

**Comment by howff** [comment]
I've looked at some SRs and seen the following tags which look like references

```
"ReferencedStudySequence":
[
  {
    "ReferencedSOPClassUID": "1.2.3",
    "ReferencedSOPInstanceUID": "1.2.3.4"
  }
]

"ReferencedImageSequence":
[
  {
    "ReferencedSOPClassUID": "1.2.3",
    "ReferencedSOPInstanceUID": "1.2.3.4"
  }
]

"SourceImageSequence":
[
  {
    "ReferencedSOPClassUID": "1.2.6",
    "ReferencedSOPInstanceUID": "1.2.6.4"
    and maybe also
    "PurposeOfReferenceCodeSequence": [ contents not especially useful ]
  }
]

"ReferencedPerformedProcedureStepSequence":
[
  {
    "ReferencedSOPClassUID": "1.2.7",
    "ReferencedSOPInstanceUID": null
  }
]

"CurrentRequestedProcedureEvidenceSequence":
[
  {
    "ReferencedSeriesSequence":
    [
      {
        "ReferencedSOPSequence":
        [
          {
            "ReferencedSOPClassUID": "1.2.9",
            "ReferencedSOPInstanceUID": "1.2.9.1"
          }
        ],
        "SeriesInstanceUID": "1.3.1"
      }
    ],
    "StudyInstanceUID": "2.1.1"
  }
]

"(4453,100c:DR Systems, Inc_)-Unknown":
has the same structure as CurrentRequestedProcedureEvidenceSequence
```

**Comment by tznind** [comment]
@howff I have added the reference pathways as columns, see: https://github.com/HicServices/DicomTypeTranslation/pull/51/commits/99f004141cf8fb20357bfd0fc1a810c3ffa626ed

**Pull request merged**
